name: 'agent_dev_seed_dbt'
version: '1.0.0'
config-version: 2
profile: 'agent_dev_seed_dbt'

model-paths: ['models']
seed-paths: ['seeds']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  agent_dev_seed_dbt:
    marts:
      +materialized: table
